### ISSUE TITLE
Can't play on desktop with m3u8

### ISSUE THREAD

**Issue by snoywing** [WadeShuler/yii2-jwplayer#3]
I tested that it works well on phone, but not desktop.
this is my code:
```
   echo JWPlayer::widget([
    'htmlOptions' => [
        'class' => 'myVideoPlayer',
    ],
    'playerOptions' => [
    'file'=> sprintf(Yii::$app->params["livedoamin"],$model->stream),
    'autostart' => true,
     "primary"=> "flash",
    ],
])
```
Is that right to play m3u8 on desktop with flash?

**Comment by WadeShuler** [comment]
I do not believe this is anything related to my extension. This extension simply generates the HTML to embed the player on your page.

According to the docs, the m3u8 streaming feature is ONLY available on mobile devices. You must have the JWPlayer Premium to use it on desktops: [https://support.jwplayer.com/customer/en/portal/articles/1403635-media-format-reference](https://support.jwplayer.com/customer/en/portal/articles/1403635-media-format-reference)

Try their stream tester: [https://developer.jwplayer.com/tools/stream-tester/](https://developer.jwplayer.com/tools/stream-tester/)

It is also important to note that m3u8 is subject to CORS, so you may have issues loading it from another domain: [https://support.jwplayer.com/customer/portal/articles/1430240-adaptive-streaming](https://support.jwplayer.com/customer/portal/articles/1430240-adaptive-streaming)

**Comment by snoywing** [comment]
OK，thank you very much
