### ISSUE TITLE
Error loading file:No playable sources found

### ISSUE THREAD

**Issue by jithu121212** [WadeShuler/yii2-jwplayer#4]
please help, Error loading file:No playable sources found ,i ensured in the network inspect that path to the file location is correct.
my view code is----------
 <div id="w0">
                    <?= JWPlayer::widget([
                        'playerOptions' => [
                            'file' => 'E:\php\yii\proj#1\backend\views\file-storage\uploads\1.mp4'
                        ]
                    ]) ?>
                </div>
my web.php code is------------
'components'=>[
 'jwplayer' => [
            'class' => 'wadeshuler\jwplayer\JWConfig',
            'key' => '/lq0VD8Briz9rSMS2ftRaI2foxKQw53JgF4EYg==',  // <-- Your Key Here!!

            'playerOptions' => [
                'autostart' => true,
                'sharing' => [
                    'sites' => ['facebook', 'twitter'],
                ],
            ],
        ]
    ],

added some js files also and my id----------
<script src="/js/jwplayer-7.8.6/jwplayer.js"></script>
<script>jwplayer.key="/lq0VD8Briz9rSMS2ftRaI2foxKQw53JgF4EYg==";</script>

**Comment by WadeShuler** [comment]
Please fix your post. Your code preview is broken and you also do not show your full view code for displaying the widget.

You don't need to include any of your own JS files... The extension loads it all for you..

**Comment by jithu121212** [comment]
[index.txt](https://github.com/WadeShuler/yii2-jwplayer/files/675279/index.txt)
[web.txt](https://github.com/WadeShuler/yii2-jwplayer/files/675280/web.txt)
![screenshot from 2016-12-28 14-32-14](https://cloud.githubusercontent.com/assets/24386580/21518242/18d5efac-cd0b-11e6-9599-5f77265b23e7.png)
here is files please resolve the problem

**Comment by WadeShuler** [comment]
The path to your file is incorrect, or check the video codec.

I am leaning towards your path being incorrect. You only put the filename, which would indicate your file would be in `/frontend/web/your-video.mp4`. If that is the case, then try to start with a slash like `/your-video.mp4`. If that doesn't work, try to use the full exact URL to it. If it still doesn't work, then check JWPlayer's supported codecs and inspect your own using MediaInfo.
